name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'
        
      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 3: Install dependencies
      - name: Analyze
        run: flutter analyze

      # Step 5: Run tests
      - name: Run tests
        run: |
          dart run build_runner build --delete-conflicting-outputs
          flutter test

      # Step 6 (Optional): Build the app (Uncomment if needed)
      # - name: Build APK
      #   run: flutter build apk --release

      # - name: Build iOS
      #   run: flutter build ios --release
